export const BERLIN_PLACEMENT = {
  SCAN_RADIUS: 240,
  RECOMPUTE_MOVEMENT_THRESHOLD: 30,
  MAX_CORNERS_PER_BUILDING: 2,
  MIN_REQUIRED_DISTANCE: 18,
  ROOF_ELEVATION_EPSILON: 0.5,
  MAX_BUILDINGS_PER_TICK: 12,
  MAX_CANDIDATES_PER_TICK: 48,
  SAME_BUILDING_DEDUPE_EPSILON: 0.75,
  DEBUG_MARKERS: {
    ENABLED_BY_DEFAULT: false,
    MAX_MARKERS: 512,
    SIZE: 2.4,
    OPACITY: 0.85,
    ACCEPTED_COLOR: 0x6df7c1,
    REJECTED_COLOR: 0xff6f91,
  },
} as const;
