import {
  PUBLIC_BERLIN_ION_ASSET_ID,
  PUBLIC_BERLIN_TILES_URL,
  PUBLIC_CESIUM_ION_TOKEN,
} from "$env/static/public";

export const WERKSCHAU_CESIUM_ION_TOKEN = PUBLIC_CESIUM_ION_TOKEN;
export const WERKSCHAU_ION_ASSET_ID = Number(PUBLIC_BERLIN_ION_ASSET_ID);
export const WERKSCHAU_TILES_URL = PUBLIC_BERLIN_TILES_URL;

export const WERKSCHAU_FLIGHT_BASE_SPEED = 12;
export const WERKSCHAU_PLAYER_SPAWN_POSITION = {
  x: 0,
  y: 100,
  z: 0,
} as const;
const WERKSCHAU_EXHIBITION_SIDE_LENGTH_METERS = 4000;
const WERKSCHAU_EXHIBITION_HALF_SIDE_METERS =
  WERKSCHAU_EXHIBITION_SIDE_LENGTH_METERS * 0.5;
export const WERKSCHAU_EXHIBITION_BOUNDS = {
  center: WERKSCHAU_PLAYER_SPAWN_POSITION,
  sideLengthMeters: WERKSCHAU_EXHIBITION_SIDE_LENGTH_METERS,
  minX:
    WERKSCHAU_PLAYER_SPAWN_POSITION.x -
    WERKSCHAU_EXHIBITION_HALF_SIDE_METERS,
  maxX:
    WERKSCHAU_PLAYER_SPAWN_POSITION.x +
    WERKSCHAU_EXHIBITION_HALF_SIDE_METERS,
  minZ:
    WERKSCHAU_PLAYER_SPAWN_POSITION.z -
    WERKSCHAU_EXHIBITION_HALF_SIDE_METERS,
  maxZ:
    WERKSCHAU_PLAYER_SPAWN_POSITION.z +
    WERKSCHAU_EXHIBITION_HALF_SIDE_METERS,
} as const;
export const WERKSCHAU_EXHIBITION_BORDER_GRID = {
  COLOR: 0xff4fd8,
  HEIGHT: 240,
  STEP: 80,
  VISIBLE_DISTANCE: 220,
} as const;
export const WERKSCHAU_EXHIBITION_BORDER_DAMPING = {
  DISTANCE: 260,
  MIN_SPEED_MULTIPLIER: 0.15,
} as const;
export const WERKSCHAU_PLAYER_HEIGHT_LIMITS = { MIN: 0, MAX: 400 } as const;
export const WERKSCHAU_CAMERA_FAR = 3200;
export const WERKSCHAU_TILE_SELECTION_FOV = 82;
export const WERKSCHAU_PUBLIC_FLIGHT_DURATION_MS = 180_000;
export const WERKSCHAU_INTRO_DURATION_SECONDS = 8;
export const WERKSCHAU_OUTRO_DURATION_SECONDS = 4;

export const WERKSCHAU_ALTITUDE_SPEED = {
  MIN_ALTITUDE: 35,
  MAX_ALTITUDE: 300,
  MIN_MULTIPLIER: 0.45,
  MAX_MULTIPLIER: 1.8,
} as const;

export const WERKSCHAU_TILE_RUNTIME = {
  ERROR_TARGET: 48,
  DOWNLOAD_JOBS: 8,
  PARSE_JOBS: 2,
  PROCESS_NODE_JOBS: 8,
  MAX_TILES_PROCESSED: 48,
  LOAD_SIBLINGS: true,
  CACHE_MIN_BYTES: 512 * 1024 * 1024,
  CACHE_MAX_BYTES: 768 * 1024 * 1024,
} as const;

export const WERKSCHAU_TILE_LOOK = {
  NEUTRAL_COLOR: 0xbeeeef,
  FLAT_SHADING: true,
  ROUGHNESS: 0.7,
  METALNESS: 0,
  OPACITY: 1,
  NEUTRAL_SHADE_AMBIENT: 0.42,
  NEUTRAL_SHADE_HEMISPHERE: 0.28,
  NEUTRAL_SHADE_DIRECTIONAL: 0.45,
  NEUTRAL_SHADE_LIGHT_DIRECTION: {
    x: -0.55,
    y: 0.8,
    z: -0.25,
  },
} as const;

export const WERKSCHAU_CONE_DATASET_BASE_URL =
  "/experiences/_visio-tech-werkschau/cone-data/generated";
export const WERKSCHAU_CONE_MIN_TILT_DEGREES = 10;
export const WERKSCHAU_CONE_MIN_TIP_HEIGHT = 110;
export const WERKSCHAU_CONE_GRID = {
  SPACING: 240,
  ORIGIN_HEIGHT: 140,
  CONE_RADIUS: 48,
  CONE_HEIGHT: 180,
  COLOR: 0xff4fd8,
  OPACITY: 0.34,
  VISIBLE_RADIUS_TILES: 6,
  CHUNK_CONES_PER_SIDE: 8,
  MAX_CHUNK_LOADS_PER_TICK: 4,
} as const;
