import {
  PUBLIC_BERLIN_ION_ASSET_ID,
  PUBLIC_BERLIN_TILES_URL,
  PUBLIC_CESIUM_ION_TOKEN,
} from "$env/static/public";

export const WERKSCHAU_CESIUM_ION_TOKEN = PUBLIC_CESIUM_ION_TOKEN;
export const WERKSCHAU_ION_ASSET_ID = Number(PUBLIC_BERLIN_ION_ASSET_ID);
export const WERKSCHAU_TILES_URL = PUBLIC_BERLIN_TILES_URL;

export const WERKSCHAU_FLIGHT_BASE_SPEED = 20;
export const WERKSCHAU_PLAYER_SPAWN_POSITION = {
  x: 0,
  y: 100,
  z: 0,
} as const;
export const WERKSCHAU_PLAYER_HEIGHT_LIMITS = { MIN: 0, MAX: 400 } as const;
export const WERKSCHAU_CAMERA_FAR = 3200;
export const WERKSCHAU_TILE_SELECTION_FOV = 82;
export const WERKSCHAU_PUBLIC_FLIGHT_DURATION_MS = 180_000;
export const WERKSCHAU_INTRO_DURATION_SECONDS = 8;
export const WERKSCHAU_OUTRO_DURATION_SECONDS = 4;

export const WERKSCHAU_ALTITUDE_SPEED = {
  MIN_ALTITUDE: 35,
  MAX_ALTITUDE: 450,
  MIN_MULTIPLIER: 0.45,
  MAX_MULTIPLIER: 3,
} as const;

export const WERKSCHAU_TILE_RUNTIME = {
  ERROR_TARGET: 48,
  DOWNLOAD_JOBS: 8,
  PARSE_JOBS: 2,
  PROCESS_NODE_JOBS: 8,
  MAX_TILES_PROCESSED: 48,
  LOAD_SIBLINGS: true,
  CACHE_MIN_BYTES: 512 * 1024 * 1024,
  CACHE_MAX_BYTES: 768 * 1024 * 1024,
} as const;

export const WERKSCHAU_TILE_LOOK = {
  NEUTRAL_COLOR: 0xbeeeef,
  FLAT_SHADING: true,
} as const;

export const WERKSCHAU_CONE_DATASET_BASE_URL =
  "/experiences/_visio-tech-werkschau/cone-data/generated";
export const WERKSCHAU_CONE_MIN_TILT_DEGREES = 10;
export const WERKSCHAU_CONE_GRID = {
  SPACING: 240,
  ORIGIN_HEIGHT: 140,
  CONE_RADIUS: 48,
  CONE_HEIGHT: 180,
  COLOR: 0xff4fd8,
  OPACITY: 0.34,
  VISIBLE_RADIUS_TILES: 14,
  CHUNK_CONES_PER_SIDE: 8,
  MAX_CHUNK_LOADS_PER_TICK: 4,
} as const;

export const WERKSCHAU_BERLIN_GEO_BOUNDS = {
  north: 52.675,
  south: 52.338,
  west: 13.088,
  east: 13.761,
} as const;
