const BERLIN_CONE_VISIBLE_RADIUS_TILES = 2;
const BERLIN_CONE_CHUNK_CONES_PER_SIDE = 8;
const BERLIN_CONE_LOAD_RADIUS_CHUNKS = Math.ceil(
  BERLIN_CONE_VISIBLE_RADIUS_TILES / BERLIN_CONE_CHUNK_CONES_PER_SIDE,
);

export const BERLIN_CONE_GRID = {
  SPACING: 240,
  ORIGIN_HEIGHT: 140,
  CONE_RADIUS: 48,
  CONE_HEIGHT: 180,
  COLOR: 0xff4fd8,
  VISIBLE_RADIUS_TILES: BERLIN_CONE_VISIBLE_RADIUS_TILES,
  CHUNK_CONES_PER_SIDE: BERLIN_CONE_CHUNK_CONES_PER_SIDE,
  LOAD_RADIUS_CHUNKS: BERLIN_CONE_LOAD_RADIUS_CHUNKS,
  UNLOAD_RADIUS_CHUNKS: BERLIN_CONE_LOAD_RADIUS_CHUNKS + 1,
  MAX_CHUNK_LOADS_PER_TICK: 3,
} as const;
