export const WERKSCHAU_COLLISION = {
  ENABLED: true,
  MAX_MESHES_PER_TICK: 32,
  TRIANGLE_MASK_SAMPLE_SPACING_METERS: 4,
  MAX_TRIANGLE_MASK_SUBDIVISIONS: 8,
  MIN_TRACKED_VERTICES: 12,
  MAX_TRACKED_VERTICES: 50_000,
  MIN_TRACKED_RADIUS: 1,
  MAX_TRACKED_RADIUS: 600,
} as const;
