import { WERKSCHAU_CONE_GRID } from "../constants";

const WERKSCHAU_CONE_LOAD_RADIUS_CHUNKS = Math.ceil(
  WERKSCHAU_CONE_GRID.VISIBLE_RADIUS_TILES /
    WERKSCHAU_CONE_GRID.CHUNK_CONES_PER_SIDE,
);

export const WERKSCHAU_CONE_RUNTIME_GRID = {
  ...WERKSCHAU_CONE_GRID,
  LOAD_RADIUS_CHUNKS: WERKSCHAU_CONE_LOAD_RADIUS_CHUNKS,
  UNLOAD_RADIUS_CHUNKS: WERKSCHAU_CONE_LOAD_RADIUS_CHUNKS + 1,
} as const;
